import type { ActiveOrderRow } from "@/types/active-orders";

export const mockActiveOrders: ActiveOrderRow[] = [
  {
    id: "order-1",
    displayId: "#7812456",
    symbol: "BTCUSD",
    icon: "bitcoin",
    side: "buy",
    type: "limit",
    qty: 0.75,
    price: 69_100,
    takeProfit: 72_500,
    stopLoss: 66_000,
    status: "filled",
  },
  {
    id: "order-2",
    displayId: "#7812457",
    symbol: "ETHUSD",
    icon: "ethereum",
    side: "buy",
    type: "limit",
    qty: 4.25,
    price: 3_680.5,
    takeProfit: 3_950,
    stopLoss: 3_420,
    status: "partial",
  },
  {
    id: "order-3",
    displayId: "#7812458",
    symbol: "SOLUSD",
    icon: "solana",
    side: "sell",
    type: "limit",
    qty: 25,
    price: 182.4,
    takeProfit: 175,
    stopLoss: 190,
    status: "filled",
  },
  {
    id: "order-4",
    displayId: "#7812459",
    symbol: "XRPUSD",
    icon: "ripple",
    side: "buy",
    type: "limit",
    qty: 12_500,
    price: 0.6124,
    takeProfit: 0.68,
    stopLoss: 0.58,
    status: "partial",
  },
  {
    id: "order-5",
    displayId: "#7812460",
    symbol: "ADAUSD",
    icon: "cardano",
    side: "sell",
    type: "limit",
    qty: 8_400,
    price: 0.7842,
    takeProfit: 0.72,
    stopLoss: 0.84,
    status: "filled",
  },
];
