import type { PortfolioMetricCard } from "@/types/portfolio-metric-card";

export const mockAnalyticsMetricCards: PortfolioMetricCard[] = [
  {
    id: "net-pnl",
    variant: "icon-stats",
    title: "Net P&L",
    value: "$12,345",
    valueTone: "positive",
    subtitle: "+12.34% this cycle",
    subtitleTone: "positive",
    iconSrc: "/images/portfolio/graph.svg",
    iconTone: "green",
    subStats: [
      { label: "Best Day", value: "$1,942", tone: "positive" },
      { label: "Avg Day", value: "$412" },
    ],
  },
  {
    id: "win-rate",
    variant: "gauge-progress",
    title: "Win Rate",
    value: "63.4%",
    subtitle: "142 trades analyzed",
    gaugeValue: 63,
    progressValue: 63,
    progressLeftLabel: "Goal",
    progressRightLabel: "50%+",
  },
  {
    id: "profit-factor",
    variant: "icon-stats",
    title: "Profit Factor",
    value: "2.35",
    subtitle: "Target 2.0+",
    iconSrc: "/images/portfolio/graph.svg",
    iconTone: "green",
    subStats: [
      { label: "Gross Profit", value: "$21.8K" },
      { label: "Gross Loss", value: "$9.3K" },
    ],
  },
  {
    id: "max-drawdown",
    variant: "icon-stats",
    title: "Max Drawdown",
    value: "$2,345",
    valueTone: "negative",
    subtitle: "-8.21%",
    subtitleTone: "negative",
    iconSrc: "/images/portfolio/risk.svg",
    iconTone: "red",
    subStats: [
      { label: "Threshold", value: "$5,000" },
      { label: "Status", value: "Safe", tone: "positive" },
    ],
  },
  {
    id: "consistency",
    variant: "icon-stats",
    title: "Consistency",
    value: "7.8/10",
    subtitle: "Improving",
    subtitleTone: "positive",
    iconSrc: "/images/momentum.svg",
    iconTone: "blue",
    subStats: [
      { label: "Green Days", value: "18" },
      { label: "Streak", value: "7 days" },
    ],
  },
  {
    id: "payout",
    variant: "icon-stats",
    title: "Payout",
    value: "Eligible",
    valueTone: "positive",
    subtitle: "Rules Passed",
    iconSrc: "/sidebar icons/cup star.svg",
    iconTone: "orange",
    subStats: [
      { label: "Next Payout", value: "Jun 28" },
      { label: "Score", value: "A+", tone: "positive" },
    ],
  },
];
