import type { OpenPositionStripItem } from "@/types/open-positions-strip";

export const mockOpenPositionsStrip: OpenPositionStripItem[] = [
  {
    id: "pos-btcusd",
    symbol: "BTCUSD",
    icon: "bitcoin",
    side: "long",
    pnl: 1695.49,
    pnlPercent: 3.21,
    sizeLabel: "0.7500 BTC",
    entryLabel: "Entry 66,842.10",
    trend: [
      { value: 42 },
      { value: 43 },
      { value: 45 },
      { value: 49 },
      { value: 51 },
      { value: 46 },
      { value: 48 },
      { value: 53 },
    ],
    palette: "profit",
  },
  {
    id: "pos-ethusd",
    symbol: "ETHUSD",
    icon: "ethereum",
    side: "long",
    pnl: 1147.62,
    pnlPercent: 2.41,
    sizeLabel: "4.2500 ETH",
    entryLabel: "Entry 3,432.21",
    trend: [
      { value: 36 },
      { value: 37 },
      { value: 40 },
      { value: 42 },
      { value: 38 },
      { value: 39 },
      { value: 43 },
      { value: 44 },
    ],
    palette: "profit",
  },
  {
    id: "pos-xrpusd",
    symbol: "XRPUSD",
    icon: "ripple",
    side: "short",
    pnl: -0.0,
    pnlPercent: -0.0,
    sizeLabel: "0.5248 XRP",
    entryLabel: "Entry 0.5428",
    trend: [
      { value: 48 },
      { value: 49 },
      { value: 48 },
      { value: 47 },
      { value: 48 },
      { value: 46 },
      { value: 45 },
      { value: 46 },
    ],
    palette: "loss",
  },
  {
    id: "pos-solusd",
    symbol: "SOLUSD",
    icon: "solana",
    side: "short",
    pnl: 152.75,
    pnlPercent: 3.21,
    sizeLabel: "25.000 SOL",
    entryLabel: "Entry 178.45",
    trend: [
      { value: 35 },
      { value: 37 },
      { value: 41 },
      { value: 44 },
      { value: 36 },
      { value: 38 },
      { value: 42 },
      { value: 47 },
    ],
    palette: "profit",
  },
];
