import type { PortfolioOpenPositionRow } from "@/types/portfolio-open-positions";

export const mockPortfolioOpenPositions: PortfolioOpenPositionRow[] = [
  {
    id: "btc-long",
    symbol: "BTCUSD",
    icon: "bitcoin",
    side: "long",
    size: 0.75,
    sizeUnit: "BTC",
    avgEntry: 66842.1,
    markPrice: 69102.75,
    leverage: 10,
    pnl: 1695.49,
    pnlPercent: 3.38,
    liquidationPrice: 64000,
    risk: "low",
  },
  {
    id: "eth-long",
    symbol: "ETHUSD",
    icon: "ethereum",
    side: "long",
    size: 4.25,
    sizeUnit: "ETH",
    avgEntry: 3432.21,
    markPrice: 3702.18,
    leverage: 8,
    pnl: 1147.62,
    pnlPercent: 7.86,
    liquidationPrice: 3090,
    risk: "low",
  },
  {
    id: "sol-short",
    symbol: "SOLUSD",
    icon: "solana",
    side: "short",
    size: 25,
    sizeUnit: "SOL",
    avgEntry: 178.45,
    markPrice: 172.34,
    leverage: 6,
    pnl: 152.75,
    pnlPercent: 3.42,
    liquidationPrice: 190,
    risk: "medium",
  },
  {
    id: "xrp-short",
    symbol: "XRPUSD",
    icon: "ripple",
    side: "short",
    size: 0.5248,
    sizeUnit: "XRP",
    avgEntry: 0.5228,
    markPrice: 0.5248,
    leverage: 5,
    pnl: 0,
    pnlPercent: 0,
    liquidationPrice: 0.6,
    risk: "medium",
  },
];
